export const ENDPOINTS = {
  AUTH: {
    LOGIN:           '/auth/login',
    REGISTER:        '/auth/register',
    LOGOUT:          '/auth/logout',
    REFRESH:         '/auth/refresh',
    ME:              '/auth/me',
    ME_PASSWORD:     '/auth/me/password',
  },
  ADMIN: {
    USERS:           '/auth/admin/users',
    USER_ROLE:       (userId: string) => `/auth/admin/users/${userId}/role`,
    USER_DEACTIVATE: (userId: string) => `/auth/admin/users/${userId}/deactivate`,
  },
  USERS: {
    LIST:   '/users',
    DETAIL: (id: string) => `/users/${id}`,
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
    SEARCH: '/users',
  },
  PROJECTS: {
    LIST:             '/projects',
    CREATE:           '/projects',
    DETAIL:           (id: string) => `/projects/${id}`,
    UPDATE:           (id: string) => `/projects/${id}`,
    ARCHIVE:          (id: string) => `/projects/${id}/archive`,
    UNARCHIVE:        (id: string) => `/projects/${id}/unarchive`,
    MEMBERS:          (id: string) => `/projects/${id}/members`,
    MEMBER:           (id: string, userId: string) => `/projects/${id}/members/${userId}`,
    MEMBER_ENV_ACCESS:(id: string, memberId: string) => `/projects/${id}/members/${memberId}/env-access`,
    ACCOUNTS:         (id: string) => `/projects/${id}/accounts`,
    ACCOUNT:          (id: string, accountId: string) => `/projects/${id}/accounts/${accountId}`,
  },
} as const
